services:
  - type: web
    name: worldcup-fullstack
    env: node
    rootDirectory: .
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: BASE_PATH
        value: "/"
      - key: NODE_ENV
        value: "production"
